---

- name: config - environmental variables
  template:
    src=environment.sh.j2
    dest=/etc/profile.d/go.sh
    owner=root
    group=root
    mode=0644

- name: dependencies
  apt:
    pkg={{ item }}
    update_cache=yes
  with_items:
    - git
    - mercurial

