---

- name: create build directory
  file:
    state=directory
    path={{ golang_build_dir }}

- name: install go with gimme
  shell: 'eval "$(curl -sL https://raw.githubusercontent.com/meatballhat/gimme/master/gimme | GIMME_GO_VERSION={{ golang_version }} bash)"'
  args:
    chdir: "{{ golang_build_dir }}"
