---
# tasks file for golang
- name: dependencies
  include: depend.yml

- name: install go manually
  include: install.yml
  when: not golang_per_user

- name: configure go manually
  include: config.yml
  when: not golang_per_user

- name: gimme go
  include: gimme.yml
  when: golang_per_user
